#!/bin/sh

echo "Running golint pre-commit hook" >&2

if ! command -v golint &> /dev/null
then
    echo "golint not installed" >&2
    echo "Options" >&2
    echo -e "\t1. Install golint: 'go get -u golang.org/x/lint/golint' and ensure that it's in your \$PATH" >&2
    echo -e "\t2. Commit using the '--no-verify' option to skip this hook" >&2
    echo "Failed to commit" >&2
    exit 1
fi

golint -set_exit_status ./... 1>&2
